title: Clase de machine Learning
logo: /images/escudo.jpg
description: Clase de Machine Learning en la Universidad Panamericana
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
